networks:
  yii2:
    driver: bridge

volumes:
  db-data:
    driver: local

services:
  nginx:
    container_name: yii_nginx
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./www:/var/www
      - ./vhost.conf:/etc/nginx/conf.d/default.conf
    networks:
      - yii2
    depends_on:
      - php
  php:
    container_name: yii_php
    build: ./images/php81fpm
    volumes:
      - ./www:/var/www
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - yii2
    depends_on:
      - db

  db:
    image: postgres:15-alpine3.17
    container_name: db-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-yii}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-yii}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - yii2
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME:-postgres} -d ${DB_NAME:-yii}" ]
      interval: 5s
      timeout: 25s
      retries: 10

  adminer:
    image: adminer
    restart: unless-stopped
    container_name: adminer-dev
    ports:
      - 8888:8080
    networks:
      - yii2